BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PORTAL_FARDAMENTO_MOVIMENTO';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PORTAL_FARDAMENTO_ESTOQUE';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PORTAL_FARDAMENTO_PRODUTO';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE PORTAL_FARD_MOV_SEQ';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE PORTAL_FARD_EST_SEQ';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE PORTAL_FARD_PROD_SEQ';
EXCEPTION
   WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;

CREATE SEQUENCE PORTAL_FARD_PROD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PORTAL_FARD_EST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PORTAL_FARD_MOV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PORTAL_FARDAMENTO_PRODUTO (
    ID              NUMBER(12)        NOT NULL,
    NOME            VARCHAR2(200)     NOT NULL,
    DESCRICAO       VARCHAR2(4000),
    UNIDADE         VARCHAR2(10)      DEFAULT 'UN' NOT NULL,
    ATIVO           CHAR(1)           DEFAULT 'S' NOT NULL,
    CRIADO_EM       TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FARD_PROD PRIMARY KEY (ID),
    CONSTRAINT CK_FARD_PROD_ATIVO CHECK (ATIVO IN ('S', 'N'))
);

CREATE TABLE PORTAL_FARDAMENTO_ESTOQUE (
    ID              NUMBER(12)        NOT NULL,
    PRODUTO_ID      NUMBER(12)        NOT NULL,
    TAMANHO         VARCHAR2(60)      DEFAULT '-' NOT NULL,
    LOCAL_REF       VARCHAR2(120)     DEFAULT '-' NOT NULL,
    QUANTIDADE      NUMBER(14, 3)     DEFAULT 0 NOT NULL,
    UPDATED_AT      TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FARD_EST PRIMARY KEY (ID),
    CONSTRAINT FK_FARD_EST_PROD FOREIGN KEY (PRODUTO_ID)
        REFERENCES PORTAL_FARDAMENTO_PRODUTO (ID) ENABLE,
    CONSTRAINT UK_FARD_EST UNIQUE (PRODUTO_ID, TAMANHO, LOCAL_REF)
);

CREATE INDEX IDX_FARD_EST_PROD ON PORTAL_FARDAMENTO_ESTOQUE (PRODUTO_ID);

CREATE TABLE PORTAL_FARDAMENTO_MOVIMENTO (
    ID              NUMBER(12)        NOT NULL,
    ESTOQUE_ID      NUMBER(12)        NOT NULL,
    TIPO            VARCHAR2(20)      NOT NULL,
    QT_MOVIMENTO    NUMBER(14, 3)     NOT NULL,
    OBSERVACAO      VARCHAR2(4000),
    USUARIO_PORTAL  VARCHAR2(120),
    MATRICULA_DEST  VARCHAR2(40),
    NOME_DEST       VARCHAR2(200),
    CRIADO_EM       TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FARD_MOV PRIMARY KEY (ID),
    CONSTRAINT FK_FARD_MOV_EST FOREIGN KEY (ESTOQUE_ID)
        REFERENCES PORTAL_FARDAMENTO_ESTOQUE (ID) ENABLE,
    CONSTRAINT CK_FARD_MOV_TIPO CHECK (TIPO IN ('ENTRADA', 'SAIDA', 'DEVOLUCAO', 'AJUSTE'))
);

CREATE INDEX IDX_FARD_MOV_EST_DATA ON PORTAL_FARDAMENTO_MOVIMENTO (ESTOQUE_ID, CRIADO_EM DESC);

COMMENT ON TABLE PORTAL_FARDAMENTO_PRODUTO IS 'Portal — tipos de peça de fardamento';

COMMENT ON TABLE PORTAL_FARDAMENTO_ESTOQUE IS 'Portal — saldo por produto + tamanho + local';

COMMENT ON TABLE PORTAL_FARDAMENTO_MOVIMENTO IS 'Portal — histórico (QT_MOVIMENTO assinado)';

COMMIT;

















